AllCops:
   Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'Gemfile'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AlignHash:
  Enable: false

Style/MultilineBlockChain:
  Enable: false
